services:
  - type: web
    name: live-waitlist-system
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_DIR
        value: .
      - key: ADMIN_USERNAME
        sync: false
        placeholder: "ohhaewon030225"
      - key: ADMIN_PASSWORD
        sync: false
        placeholder: "nmixxbestleader"
